### ISSUE TITLE
Add data_from_url option for Smart Cell Chart

### ISSUE THREAD

**Issue by joeybellerose** [livebook-dev/kino_vega_lite#17]
It would be awesome to have an option for the Smart Cell Chart to provide an option to use VegaLites `data_from_url`.  This way data doesn't have to be only local.  We could chart external data sources.  

For example here's a [huge list](https://vincentarelbundock.github.io/Rdatasets/datasets.html) that the R community maintains.
It would be great to chart these without having to download them. 👍

**Comment by josevalim** [comment]
Maybe we can detect if a variable is a string and, if so, use it as a URL? A pull request along those lines would be welcome!

**Comment by josevalim** [comment]
We are not planning to do this for now because we do many things related to data inference. Perhaps the best step is to load this data into an Explorer dataframe first!
