### ISSUE TITLE
Initial render of smart chart cell source code is incorrect

### ISSUE THREAD

**Issue by aedwardg** [livebook-dev/kino_vega_lite#18]
### Bug

When creating a new smart chart cell, the initial render of source code is incorrect when clicking on the "Toggle source" button.
Joining the Livebook session in a new tab or converting the cell to a code cell fixes the rendered source code.

Not sure if this is specific to smart chart cells or a broader problem, but these are the only smart cells I've tried the "Toggle source" button on.

#### Minimal data used for reproducing bug

```elixir
goals_test = [
  %{goals: 4, year: 1930},
  %{goals: 1, year: 1930},
  %{goals: 2, year: 1950},
  %{goals: 4, year: 1950},
  %{goals: 3, year: 1962},
  %{goals: 4, year: 1962}
]
```

#### Steps to reproduce

1. Save minimal data as a variable
2. Create new kino_vega_lite smart chart cell and fill out UI fields
3. Click "Toggle source"
4. See incorrect source code
5. Convert cell to a code cell or join Livebook in a new tab
6. See correct source code

#### System specs
Elixir: 1.13.4
Livebook: 0.6.3
kino_vega_lite: 0.1.3
Browsers: Firefox, Chrome
OS: WSL2 Ubuntu 20.04

### Screenshots
UI fields:

![image](https://user-images.githubusercontent.com/44326005/185809794-d6378402-a923-4c13-9dbf-59abc4e85d1a.png)

"Toggle source" clicked:

![image](https://user-images.githubusercontent.com/44326005/185809824-308a7f24-0f57-4811-8c3e-bf8af81608f4.png)

Two tabs opened to the same session side by side:

![image](https://user-images.githubusercontent.com/44326005/185810109-3c64295f-d8b6-45bb-86df-e8c1758a3321.png)

**Comment by josevalim** [comment]
Thanks for the great report!

I believe this is an issue related to newlines on Windows vs Unix. Right @jonatanklosko?

**Comment by jonatanklosko** [comment]
@josevalim changes to the source are applied as diffs, and multiple manipulations are multiple diffs, so this definitely seems like the newlines issue.

@aedwardg can you please try to run livebook from the main branch and verify that it's no longer an issue? :)

**Comment by aedwardg** [comment]
@jonatanklosko I'll try to take a look after work. 

This morning I tried downloading Livebook main branch using Escript, but I got an error in the console saying it required Elixir 1.14.0rc. I then noticed that `rebar2` support was [removed in 1.14.0rc0](https://github.com/elixir-lang/elixir/releases/tag/v1.14.0-rc.0).  Does this mean I won't be able to follow the [Escript installation instructions](https://github.com/livebook-dev/livebook#escript) to download Livebook main branch, or will those still work?

**Comment by jonatanklosko** [comment]
@aedwardg do you mean you're forced to use rebar2, otherwise it should all work fine. Alternatively you can try in using the Docker image.

**Comment by josevalim** [comment]
@aedwardg it should all just work. Rebar2 is no longer supported but everything uses Rebar3 nowadays. :)

**Comment by aedwardg** [comment]
@josevalim @jonatanklosko, yes it seems to work fine with everything updated to the newest versions: 

- Elixir: 1.14.0-rc.1-otp-25
- Livebook: `main` branch 

Thanks for the help and sorry for the confusion!
