### ISSUE TITLE
Optionally disable the livebook theme

### ISSUE THREAD

**Issue by pnezis** [livebook-dev/kino_vega_lite#55]
It was [reported in Tucan](https://github.com/pnezis/tucan/issues/21) that some themes do not render properly. After some investigation it seems that the reason is that `kino_vega_lite` [applies a default theme](https://github.com/livebook-dev/kino_vega_lite/blob/dab662c67e5f81dd3b85b193812b1527d6a84d8f/assets/vega_lite/main.js#L52), which may overwrite the Tucan themes settings based on [`vega-lite` precedence settings](https://vega.github.io/vega-lite/docs/axis.html#config).

I am not sure if this is possible, but a possible workaround would be to conditionally apply the livebook theme. For example:

```elixir
KinoVegaLite.configure(apply_default_theme: false)
```

If this is doable, and you agree with this, I can have a look into it (even though JS is not my thing 😄  )

**Comment by jonatanklosko** [comment]
Hey, I think we can have `Kino.VegaLite.configure(theme: nil | :livebook)`, with `:livebook` being the default. A PR is welcome!

**Comment by pnezis** [comment]
Sounds good, will send a PR the following days.
